### PR TITLE
DDD: Board Bowser's Sub will now always spawn the sub and not the poles

### PR DESCRIPTION
**Pull request by soopercool101**
When entering DDD Act 1, this change makes it load a different submarine that does not have the deletion logic, resulting in the submarine remaining there on Act 1 regardless of checked locations. This fixes a bug in the latest APWorld which presumes that you will be able to collect the red coins using the submarine if strict move requirements are off. Additionally, the poles have been changed to only allow spawning on later acts.

I did not change the way the submarine exit is handled, it will still be missing if all requirements are met even if Board Bowser's Sub has been selected. This was done because A) Changing how the whirlpool spawns would require developing a new macro and B) This exit door does not affect any possible locations. so whether it's there or not is ultimately no consequence

This does not affect the same files as the nonstop patch and has been tested and confirmed working with all official patches. Due to the way acts are loaded in SM64 it is now significantly more difficult to be put in the position that the first change in #8 fixed, but it is still possible if BitFS Key location gets collected mid-level, so I elected to leave those edits in.

### CODE REVIEW

**Comment by soopercool101** [comment]
Actually, come to think of it, now the only situations in which the submarine leaves mid-level are not specific to nonstop mode (`collect`, `send_location`, and multiple players on a single slot are all viable ways to achieve this result). As such, I'm going to move the first change in #8 from the nonstop patch directly to the main game instead

**Comment by N00byKing** [comment]
Instead of adding a dummy behavior, you can modify the behavior script and differentiate acts using a parameter (behParam in the script file). You can look at the way the clock hands are implemented for reference.
Additionally, what are the changes to the pole behavior for?

**Comment by soopercool101** [comment]
Alright the implementation now uses alternate behParams instead of duplicated behaviors.

The pole changes make it so that they are able to spawn-in mid level much in the same way that the submarine can be despawned midlevel. This now only occurs in rare cases (including `collect`, `send_location`, and multiple players on a single slot) but considering this work was already done and approved prior, I figured I'd change it here since the only remaining ways this can happen are not nonstop exclusive (prior the most likely way to encounter this would be to collect the submarine star after BitFS has been completed, thus despawning the submarine, as noted in the original change #8). After these latest changes, because Act 1 will always be the loaded one if the sub star has not been collected, this original issue will no longer happen, and the submarine will not despawn upon collecting the star in Nonstop mode.

If you'd like, I can revert to vanilla behavior, which will result in rare cases in which neither the submarine nor poles are spawned, but this would be fixable by simply re-entering the level. Barely an issue but considering there's already a well-tested fix I figured I'd include it.

**Comment by N00byKing** [comment]
Sounds very reasonable. Thanks!

**Pull request merged**
